name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}    
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Assume AWS IAM Role
      id: assume-role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::970547334392:role/github_actions
        role-skip-session-tagging: true
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        #role-external-id: external-id-value  # Optional, only if the role requires an external ID

    # - name: Set ECR Registry URI
    #   run: echo "ECR_REGISTRY_URI=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_ENV

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: 970547334392.dkr.ecr.eu-north-1.amazonaws.com/idp/api-imdb:latest



env:
  REPOSITORY_NAME: api-imdb